# Generated by Django 4.0.6 on 2022-07-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_user_details_kcno'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('remarks', models.CharField(max_length=500)),
                ('dt', models.CharField(max_length=20)),
                ('tm', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='house_agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('ag_dt', models.CharField(max_length=20)),
                ('rent_dt', models.CharField(max_length=20)),
                ('rent_advance', models.FloatField()),
                ('rent_amt', models.FloatField()),
                ('duration', models.IntegerField()),
                ('dt', models.CharField(max_length=20)),
                ('tm', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='house_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('house_name', models.CharField(max_length=100)),
                ('house_type_id', models.IntegerField()),
                ('rent_amt', models.FloatField()),
                ('rent_advance', models.CharField(max_length=100)),
                ('addr1', models.CharField(max_length=500)),
                ('addr2', models.CharField(max_length=500)),
                ('addr3', models.CharField(max_length=500)),
                ('pin', models.CharField(max_length=10)),
                ('house_descp', models.CharField(max_length=500)),
                ('house_rules', models.CharField(max_length=500)),
                ('house_facilities', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='house_manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('addr', models.CharField(max_length=1000)),
                ('pin', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=250)),
                ('contact', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='house_messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_request_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=500)),
                ('dt', models.CharField(max_length=20)),
                ('tm', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='house_pics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_id', models.IntegerField()),
                ('pic_path', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='house_pool_advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('house_id', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('descp', models.CharField(max_length=500)),
                ('rent_amt', models.FloatField()),
                ('dt', models.CharField(max_length=20)),
                ('tm', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='house_pool_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_agreement_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('dt', models.CharField(max_length=20)),
                ('tm', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='house_pooling_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_pool_add_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('msg', models.CharField(max_length=500)),
                ('dt', models.CharField(max_length=20)),
                ('tm', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='house_rent_payment_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_agreement_id', models.IntegerField()),
                ('remarks', models.CharField(max_length=500)),
                ('dt', models.CharField(max_length=20)),
                ('tm', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='house_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('remarks', models.CharField(max_length=1000)),
                ('dt', models.CharField(max_length=20)),
                ('tm', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='house_type',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='transaction_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('ref_id', models.IntegerField()),
                ('amt', models.FloatField()),
                ('card', models.CharField(max_length=20)),
                ('cvv', models.CharField(max_length=10)),
                ('dt', models.CharField(max_length=20)),
                ('tm', models.CharField(max_length=20)),
                ('t_type', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user_docs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('doc_file', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='age',
        ),
        migrations.AddField(
            model_name='user_details',
            name='dob',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='status',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_details',
            name='contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='email',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='pin',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='user_login',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
